### ISSUE TITLE
Not related  much, but can you upload dotfiles? love your setup.

### ISSUE THREAD

**Issue by BlueFalconHD** [ayushhroyy/elegantfox#2]

**Comment by ayushhroyy** [comment]
if im right, the whitesur theme I use has some per-requisites and requires building in first install 
other than that, I only use dash to dock and fildem for global menu
[theme](https://github.com/vinceliuice/WhiteSur-gtk-theme)
[dash-to-dock](https://extensions.gnome.org/extension/307/dash-to-dock/)
[fildem guide normal one doesnt work](https://www.linuxuprising.com/2021/02/how-to-install-fildem-global-menu-and.html)
